baseURL = 'https://diaryofthemossking.github.io/'
locale = 'en-us'
title = 'Diary of the Moss King'

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    style = "dracula"
    noClasses = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'